name: patch
description: A wrapper for copyWith arguments, so that a nullable field can be cleared as well as replaced.
version: 1.0.0
repository: https://github.com/andyhorn/patch
issue_tracker: https://github.com/andyhorn/patch/issues

topics:
  - copywith
  - immutability
  - data-classes

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.19.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.3.0
