name: patch
description: A wrapper for copyWith arguments, so that a nullable field can be cleared as well as replaced.
version: 1.0.0
repository: https://github.com/andyhorn/patch
issue_tracker: https://github.com/andyhorn/patch/issues

environment:
  sdk: ^3.13.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
